import "./globals.css";

export const metadata = {
  title: "1Tsunami Temp Mail",
  description: "Generated by 1Tsunami",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
